import type { Item } from '../Item';

export const corruptedItems: Item[] = [
	{ name: 'Chaotic Shard', category: 'crafting material' },
	{ name: 'Eldritch Vial', category: 'potion' },
	{ name: 'Cursed Coin', category: 'coin' },
	{ name: 'Abyssal Scroll', category: 'scroll' },
	{ name: 'Wailing Dagger', category: 'one-handed weapon' },
	{ name: 'Phantom Mirror', category: 'accessory' },
	{ name: 'Shadowfire Orb', category: 'accessory' },
	{ name: 'Soulbinder Chains', category: 'accessory' },
	{ name: 'Doomed Relic', category: 'crafting material' },
	{ name: 'Chaos Tear', category: 'crafting material' },
	{ name: 'Crimson Heartstone', category: 'accessory' },
	{ name: 'Netherfire Crystal', category: 'accessory' },
	{ name: 'Whispering Skull', category: 'accessory' },
	{ name: 'Spectral Amulet', category: 'accessory' },
	{ name: "Plaguebringer's Vial", category: 'potion' },
	{ name: 'Frostbound Blade', category: 'one-handed weapon' },
	{ name: 'Voidbound Relic', category: 'crafting material' },
	{ name: 'Eclipse Gem', category: 'accessory' },
	{ name: 'Soulshatter Shard', category: 'crafting material' },
	{ name: 'Abyssal Crown', category: 'helmet' },
	{ name: 'Dreadfire Ember', category: 'accessory' },
	{ name: 'Wraithfang Dagger', category: 'one-handed weapon' },
	{ name: 'Cursed Idol', category: 'accessory' },
	{ name: 'Infernal Rune', category: 'scroll' },
	{ name: 'Bloodmoon Crystal', category: 'accessory' },
	{ name: 'Eldritch Chalice', category: 'accessory' },
	{ name: 'Chaos Core', category: 'crafting material' },
	{ name: 'Soulbound Ring', category: 'accessory' },
	{ name: 'Enigmatic Relic', category: 'crafting material' },
	{ name: 'Dreadshade Cloak', category: 'body armour' },
	{ name: 'Cursed Dagger', category: 'one-handed weapon' },
	{ name: 'Blighted Amulet', category: 'accessory' },
	{ name: 'Voidfire Shard', category: 'crafting material' },
	{ name: 'Necrotic Scroll', category: 'scroll' },
	{ name: 'Chaosbane Gem', category: 'accessory' },
	{ name: 'Ebon Veil', category: 'accessory' },
	{ name: 'Corrupted Crystal', category: 'crafting material' },
	{ name: "Plaguebringer's Robe", category: 'body armour' },
	{ name: 'Cryptic Sigil', category: 'accessory' },
	{ name: 'Soulbound Amulet', category: 'accessory' },
	{ name: 'Wailing Scepter', category: 'one-handed weapon' },
	{ name: 'Ebonfire Ember', category: 'accessory' },
	{ name: 'Abyssal Sigil', category: 'accessory' },
	{ name: 'Shroud of Desolation', category: 'body armour' },
	{ name: 'Cursed Coin Purse', category: 'accessory' },
	{ name: 'Eldritch Gem', category: 'accessory' },
	{ name: 'Frostbite Blade', category: 'one-handed weapon' },
	{ name: 'Soulbane Elixir', category: 'potion' },
	{ name: 'Chaos Pendant', category: 'accessory' },
	{ name: 'Tainted Scepter', category: 'one-handed weapon' }
];
