export const feyfolkNames = [
	'Enchanted Spriggan',
	'Feybound Trickster',
	'Nymphal Enchantress',
	'Gloomwing Sylph',
	'Thorned Pixie',
	'Ethereal Wisp',
	'Briarheart Dryad',
	'Whisperwind Harbinger',
	'Luminous Fae',
	'Moonlit Sprite',
	'Verdant Naiad',
	'Sylvan Wardancer',
	'Feyblade Enforcer',
	'Starlight Guardian',
	'Dreamweaver Sorceress',
	'Sylvan Archdruid',
	'Twilight Shifter',
	'Mystic Seelie',
	'Feywarden Keeper',
	'Gossamer Specter'
];
