export const mechanoidNames = [
	'Cogwork Enforcer',
	'Steamforged Guardian',
	'Automaton Brute',
	'Gyromech Marauder',
	'Mechanical Saboteur',
	'Geargrinder Construct',
	'Steamblade Assassin',
	'Cogheart Brawler',
	'Arcane Machinist',
	'Cogwheel Warlock',
	'Clockwork Sentry',
	'Pneumatic Artillerist',
	'Scrapmetal Scrapper',
	'Techno Warden',
	'Ebonsteel Inquisitor',
	'Mechanized Juggernaut',
	'Electric Arcanist',
	'Automated Dreadnought',
	'Steam-Powered Reaver',
	'Gearlock Tinkerer'
];
